on: [push, pull_request]
name: build
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run LuaCheck
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          luacheckrc_url: ""
